#!/bin/bash

# Define the output file
OUTPUT_FILE="$HOME/dotfiles/hyprland/monitors.conf"

# Clear the existing file or create a new one
echo "# This file is automatically generated by the monitor_config_script.sh" > "$OUTPUT_FILE"
echo "# Do not edit manually unless you know what you're doing!" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Get monitor information in JSON format
MONITORS_JSON=$(hyprctl monitors -j)

# Parse the JSON and generate monitor settings
echo "$MONITORS_JSON" | jq -r '.[] | "monitor=\(.name),\(.width)x\(.height)@\(.refreshRate | floor),\(.x)x\(.y),\(.scale)"' >> "$OUTPUT_FILE"